(defvar *wm-list*)
(setf *wm-list* '(
  (word-mora-a-R-ke-R-do-a-0-4 ISA word-mora wm-word a-R-ke-R-do wm-mora a head-posi 0 tail-posi 4)
  (word-mora-a-R-ke-R-do-do-4-0 ISA word-mora wm-word a-R-ke-R-do wm-mora do head-posi 4 tail-posi 0)
  (word-mora-o-R-rudo-o-0-3 ISA word-mora wm-word o-R-rudo wm-mora o head-posi 0 tail-posi 3)
  (word-mora-o-R-rudo-do-3-0 ISA word-mora wm-word o-R-rudo wm-mora do head-posi 3 tail-posi 0)
  (word-mora-kizi-ki-0-1 ISA word-mora wm-word kizi wm-mora ki head-posi 0 tail-posi 1)
  (word-mora-kizi-zi-1-0 ISA word-mora wm-word kizi wm-mora zi head-posi 1 tail-posi 0)
  (word-mora-kokuzei-ko-0-3 ISA word-mora wm-word kokuzei wm-mora ko head-posi 0 tail-posi 3)
  (word-mora-kokuzei-i-3-0 ISA word-mora wm-word kokuzei wm-mora i head-posi 3 tail-posi 0)
  (word-mora-sjousjuu-sjo-0-3 ISA word-mora wm-word sjousjuu wm-mora sjo head-posi 0 tail-posi 3)
  (word-mora-sjousjuu-u-3-0 ISA word-mora wm-word sjousjuu wm-mora u head-posi 3 tail-posi 0)
  (word-mora-se-N-takukamoku-se-0-6 ISA word-mora wm-word se-N-takukamoku wm-mora se head-posi 0 tail-posi 6)
  (word-mora-se-N-takukamoku-ku-6-0 ISA word-mora wm-word se-N-takukamoku wm-mora ku head-posi 6 tail-posi 0)
  (word-mora-ture-tu-0-1 ISA word-mora wm-word ture wm-mora tu head-posi 0 tail-posi 1)
  (word-mora-ture-re-1-0 ISA word-mora wm-word ture wm-mora re head-posi 1 tail-posi 0)
  (word-mora-ne-Q-to-ne-0-2 ISA word-mora wm-word ne-Q-to wm-mora ne head-posi 0 tail-posi 2)
  (word-mora-ne-Q-to-to-2-0 ISA word-mora wm-word ne-Q-to wm-mora to head-posi 2 tail-posi 0)
  (word-mora-hueapure-hu-0-4 ISA word-mora wm-word hueapure wm-mora hu head-posi 0 tail-posi 4)
  (word-mora-hueapure-re-4-0 ISA word-mora wm-word hueapure wm-mora re head-posi 4 tail-posi 0)
  (word-mora-migimawari-mi-0-4 ISA word-mora wm-word migimawari wm-mora mi head-posi 0 tail-posi 4)
  (word-mora-migimawari-ri-4-0 ISA word-mora wm-word migimawari wm-mora ri head-posi 4 tail-posi 0)
  (word-mora-ri-N-situ-ri-0-3 ISA word-mora wm-word ri-N-situ wm-mora ri head-posi 0 tail-posi 3)
  (word-mora-ri-N-situ-tu-3-0 ISA word-mora wm-word ri-N-situ wm-mora tu head-posi 3 tail-posi 0)
))
