(defvar *word-list*)
(setf *word-list* '( 
  (a-R-ke-R-do ISA word word-concept a-R-ke-R-do word-sound "アーケード")
  (o-R-rudo ISA word word-concept o-R-rudo word-sound "オールド")
  (kizi ISA word word-concept kizi word-sound "キジ")
  (kokuzei ISA word word-concept kokuzei word-sound "コクゼイ")
  (sjousjuu ISA word word-concept sjousjuu word-sound "ショウシュウ")
  (se-N-takukamoku ISA word word-concept se-N-takukamoku word-sound "センタクカモク")
  (ture ISA word word-concept ture word-sound "ツレ")
  (ne-Q-to ISA word word-concept ne-Q-to word-sound "ネット")
  (hueapure ISA word word-concept hueapure word-sound "フエアプレ")
  (migimawari ISA word word-concept migimawari word-sound "ミギマワリ")
    (ri-N-situ ISA word word-concept ri-N-situ word-sound "リンシツ")
))